name: mcarus-stack
distribution_spec:
  description: ''
  docker_image: null
  providers:
    inference: meta-reference
    safety: meta-reference
    agents: meta-reference
    memory: meta-reference
    telemetry: meta-reference
image_type: docker
